In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/bike-sharing-demand/sampleSubmission.csv
/kaggle/input/competitions/bike-sharing-demand/train.csv
/kaggle/input/competitions/bike-sharing-demand/test.csv

# Load and inspect data

In [2]:
train = pd.read_csv("/kaggle/input/competitions/bike-sharing-demand/train.csv")
test = pd.read_csv("/kaggle/input/competitions/bike-sharing-demand/test.csv")
submission = pd.read_csv("/kaggle/input/competitions/bike-sharing-demand/sampleSubmission.csv")

**Understand data**

In [3]:
train.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

In [4]:
train.tail()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [5]:
train.describe()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
count,10886.000000,10886.000000,10886.000000,10886.000000,10886.00000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000
mean,2.506614,0.028569,0.680875,1.418427,20.23086,23.655084,61.886460,12.799395,36.021955,155.552177,191.574132
std,1.116174,0.166599,0.466159,0.633839,7.79159,8.474601,19.245033,8.164537,49.960477,151.039033,181.144454
min,1.000000,0.000000,0.000000,1.000000,0.82000,0.760000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,0.000000,1.000000,13.94000,16.665000,47.000000,7.001500,4.000000,36.000000,42.000000
50%,3.000000,0.000000,1.000000,1.000000,20.50000,24.240000,62.000000,12.998000,17.000000,118.000000,145.000000
75%,4.000000,0.000000,1.000000,2.000000,26.24000,31.060000,77.000000,16.997900,49.000000,222.000000,284.000000
max,4.000000,1.000000,1.000000,4.000000,41.00000,45.455000,100.000000,56.996900,367.000000,886.000000,977.000000

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    10886 non-null  object
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB

**Check missing vlaues**

In [7]:
train.isnull()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
10881,False,False,False,False,False,False,False,False,False,False,False,False
10882,False,False,False,False,False,False,False,False,False,False,False,False
10883,False,False,False,False,False,False,False,False,False,False,False,False
10884,False,False,False,False,False,False,False,False,False,False,False,False
10885,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
train.isnull().sum()

datetime      0
season        0
holiday       0
workingday    0
weather       0
temp          0
atemp         0
humidity      0
windspeed     0
casual        0
registered    0
count         0
dtype: int64

**Feature engineering for both training /testing dataset**

In [9]:
def add_time_features(df):
    df=df.copy()
#datetime string ko proper datetime mein badlo
    df['datetime']=pd.to_datetime(df['datetime'])
    df['hour'] = df['datetime'].dt.hour
    df['month'] = df['datetime'].dt.month
    df['year'] = df['datetime'].dt.year
    df['dayofweek'] = df['datetime'].dt.dayofweek
    #now delete datetime column
    df= df.drop('datetime',axis = 1)
    return df

train = add_time_features(train)
test = add_time_features(test)

In [10]:
train.columns.tolist()

['season',
 'holiday',
 'workingday',
 'weather',
 'temp',
 'atemp',
 'humidity',
 'windspeed',
 'casual',
 'registered',
 'count',
 'hour',
 'month',
 'year',
 'dayofweek']

In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      10886 non-null  int64
 1   holiday     10886 non-null  int64
 2   workingday  10886 non-null  int64
 3   weather     10886 non-null  int64
 4   temp        10886 non-null  float64
 5   atemp       10886 non-null  float64
 6   humidity    10886 non-null  int64
 7   windspeed   10886 non-null  float64
 8   casual      10886 non-null  int64
 9   registered  10886 non-null  int64
 10  count       10886 non-null  int64
 11  hour        10886 non-null  int32
 12  month       10886 non-null  int32
 13  year        10886 non-null  int32
 14  dayofweek   10886 non-null  int32
dtypes: float64(3), int32(4), int64(8)
memory usage: 1.1 MB

# Train/split

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X = train.drop(['count', 'casual','registered'], axis = 1)
y = train['count']

In [14]:
len(X)

10886

In [15]:
len(y)

10886

In [16]:
X_test = test

In [17]:
X.shape

(10886, 12)

In [18]:
y.shape

(10886,)

In [19]:
X_test.shape

(6493, 12)

In [20]:
X.columns.tolist() == X_test.columns.tolist()

True

In [21]:
from sklearn.metrics import mean_squared_log_error

In [22]:
X_train, X_val, y_train, y_val = train_test_split(X,y,test_size = 0.2, random_state = 42)

In [23]:
from sklearn.ensemble import RandomForestRegressor

In [24]:
regressor = RandomForestRegressor(n_estimators = 100,  random_state = 42)
regressor.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [25]:


val_pred = np.clip(regressor.predict(X_val), 0, None)

In [26]:
rmsle = np.sqrt(mean_squared_log_error(y_val, val_pred))
print(f"Local RMSLE: {rmsle:.4f}")

Local RMSLE: 0.3290

In [27]:
regressor = RandomForestRegressor(n_estimators = 100,  random_state = 42)
regressor.fit(X, y)

RandomForestRegressor(random_state=42)

In [28]:
test_pred =np.clip(regressor.predict(X_test), 0, None)

In [29]:
original_test = pd.read_csv("/kaggle/input/competitions/bike-sharing-demand/test.csv")

In [30]:
submission = pd.DataFrame({
    'datetime': original_test['datetime'],
    'count': test_pred
})

In [31]:
submission.head(10)

              datetime   count
0  2011-01-20 00:00:00   10.57
1  2011-01-20 01:00:00    5.42
2  2011-01-20 02:00:00    4.44
3  2011-01-20 03:00:00    3.29
4  2011-01-20 04:00:00    3.05
5  2011-01-20 05:00:00    5.88
6  2011-01-20 06:00:00   35.21
7  2011-01-20 07:00:00   87.13
8  2011-01-20 08:00:00  191.10
9  2011-01-20 09:00:00  116.72

In [32]:
submission.shape

(6493, 2)

In [33]:
submission.columns.tolist()

['datetime', 'count']

In [34]:
(submission['count']<0).sum()

np.int64(0)

In [35]:
submission.to_csv('/kaggle/working/submission.csv', index=False)

In [36]:
# log version to improve results

In [37]:
model_log = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model_log.fit(X, np.log1p(y))

RandomForestRegressor(n_jobs=-1, random_state=42)

In [38]:
test_preds_log = np.expm1(model_log.predict(X_test))   # expm1 = exp() - 1
test_preds_log = np.clip(test_preds_log, 0, None)

In [39]:
submission2 = pd.DataFrame({
    'datetime': original_test['datetime'],
    'count':    test_preds_log
})

In [40]:
submission2.to_csv('/kaggle/working/submission_log.csv', index=False)